services:
  postgres:
    image: postgres:13.3-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
